### ISSUE TITLE
ALFA overwrites existing log entries on each pass

### ISSUE THREAD

**Issue by paulihme** [invictus-ir/ALFA#11]
When performing collection, log files are opened with the "w+" parameter.  

`with open(rel_path(save_path, logtype + ".json"), "w+") as f:
`

If there are > 1,000 entries for a given log type, they are overwritten on each pass, resulting on only a small subset of the logs being present once the collection is complete.  This an be fixed by opening with the "a" (append) parameter instead:

`with open(rel_path(save_path, logtype + ".json"), "a") as f:`

**Comment by TobiasInvictus** [comment]
> Fixing issue #11 where logs get overwritten on each pass.

Hi @paulihme, thank you very much for your finding and fix. The behavior described is indeed not wanted and I see that the fix you provided works.
