### ISSUE TITLE
Adding collection for Gmail app

### ISSUE THREAD

**Issue by ofir0S** [invictus-ir/ALFA#3]
Hi and thank you for your contribution!
I've noticed there are no logs collected for the Gmail app in the 'config.yml'.
It will be great if you can add it to ALFA!

**Comment by invictus-korstiaan** [comment]
Hi @ofir0S thank you for creating the issues, do you know what the name of that category of events is? Also in the Admin Console there are various Gmail tables can you show me which one you mean?

**Comment by invictus-korstiaan** [comment]
I looked into this and from some Google docs I found 21 API's we can retrieve data from: 
https://github.com/googleapis/google-api-dotnet-client/blob/main/Src/Generated/Google.Apis.Admin.Reports.reports_v1/Google.Apis.Admin.Reports.reports_v1.cs
Which is the same list that we're currently acquiring.

**Comment by invictus-korstiaan** [comment]
Also this one doesn't have it:
https://developers.google.com/admin-sdk/reports/reference/rest/v1/activities/list?apix_params=%7B%22userKey%22%3A%22all%22%2C%22applicationName%22%3A%22token%22%7D#applicationname
