### ISSUE TITLE
Google Cloud Shell installation - redirect URL for GCP project

### ISSUE THREAD

**Issue by nilldot** [invictus-ir/ALFA#5]
Hi,
The installation was a breeze on the Google CLoud shell instance. After adding the credential (JSON) file, I need to Oauth it via the generated (using alfa acquire) link that features the Please visit this URL to authorize this application text: https://accounts*. After visiting the URL, I get page not found, as http://localhost:8089/ is not reachable. Any suggestions on how to install it in Cloud Shell environment/?
Note. I tried to set HTTP://localhost as a redirect on the GVP, but it seems the app is hardcoded.
Thank you!

![image](https://github.com/invictus-ir/ALFA/assets/7556399/46a6f3cd-6177-4fd2-95f3-bcff06b67047)

**Comment by nilldot** [comment]
The returned URL is localhost:8089/?state=xTs6GTvSI8ynhIK7EhBv*, which I imagine causing trouble for macOS system

**Comment by nilldot** [comment]
Quick update.

I have installed this on macOS (had to use sudo, as otherwise alfa never appeared as an executable). The alfa acquire authorisation worked. Great!

Now, it seems command hangs after the access_transparency:      xx activities line
 
![issues_alfa](https://github.com/invictus-ir/ALFA/assets/7556399/8d530bbb-4fff-4af2-b3c7-0dd653caf4de)

I have copied the credentials.json and token.json files to Google cloud config/folder, which is a Linux (Debian-based Linux) box. The alfa acquire works in general, but also hangs on the same line. It seems the issue is not macOS related at this stage.

**Comment by invictus-korstiaan** [comment]
Wow so sorry I didn't get a notification for this issue. Will do some testing, but we don't support it outside Linux distributions officially. Will test it on Ubuntu where it should work if not we have more issues.

**Comment by invictus-korstiaan** [comment]
Coming back to this issue, sometimes it seems like it hangs. Could you try for instance changing the config file and only acquire let's say drive logs and see if it successfully completes?

**Comment by invictus-korstiaan** [comment]
No update/activity, if still an issue please update.
