### ISSUE TITLE
Aquire -l options and CSV format Questions 

### ISSUE THREAD

**Issue by marbaugh** [invictus-ir/ALFA#8]
I was testing the tool and was wondering if there is a full list of options for the alfa acquire -l command

Also with the logs being saved in JSON, do you have any recommendations on getting it into CSV format?  Or could this be an output option?

**Comment by invictus-korstiaan** [comment]
Hi Marbaugh, thanks for this and sorry for the late reply, we're a bit busy.
We want to improve the documentation later and move it to readthedocs so we can properly write everything down. As a solution for now you could inspect the code (https://github.com/invictus-ir/ALFA/blob/main/alfa/cmdline.py) if you're looking for which services you can acquire logging from take a look at the https://github.com/invictus-ir/ALFA/blob/main/alfa/config/config.yml this has a list of the logs.
